content:
  - name: nuggets
    label: Nuggets
    path: src/content/nuggets
    type: collection
    filename: '{year}-{month}-{day}-{hour}-{minute}.md'
    fields:
      - name: nugget
        type: text
        required: true
      - label: Nugget
        name: body
        type: text